### ISSUE TITLE
特性需求:支持数位板

### ISSUE THREAD

**Issue by yanyu2015** [dicarne/sy-canvas#1]
1早上看到有手写功能挂件，体验了一把。
似乎目前仅支持鼠标绘图，无法支持数位板的笔(拿了和冠的试了下)
要是能支持类似于bookxnote或drawboard的手写体验，那真是太棒了，所以请求支持数位板。
2建议颜色设置提供几个主要的常用颜色，不然每次通过rgb选择不利于统一

**Comment by dicarne** [comment]
数位板应该可以试试支持，我回去看一下怎么做，但压感没戏。颜色设置主要是因为挂件的局限性，好像不能同步，还没有很好的解决方案，只能期待D大的更新。不过将设置保存在当前块是可以做的。

**Comment by dicarne** [comment]
[https://github.com/siyuan-note/bazaar/pull/182](https://github.com/siyuan-note/bazaar/pull/182)
修复了数位板不能正常画图的问题，在我的数位板上正常了。
另外现在可以通过代码块配置自己的画板，选择自己喜欢的颜色。在挂件内就不提供配置功能了，用的组件库没这个功能我又懒得实现。
可能需要重新安装挂件使其生效，另外，思源的缓存似乎没更新，还需要一定时间（可能明天）才能下载到最新的挂件。

**Comment by dicarne** [comment]
现在重新安装挂件后即可更新成功
