### ISSUE TITLE
对该挂件的小小的建议

### ISSUE THREAD

**Issue by sun7sun7sun7sun7** [dicarne/sy-canvas#3]
sy-canvas的制作者，你好。
非常感谢你制作了这么好的一个挂件，有了你的挂件，思源笔记好用了很多。
我想提两个小小的建议：sy-canvas挂件，如果画图时右键能变成像橡皮一样擦除，那就完全满足手写或绘图的基本需求了。另外，该挂件锁定后，“解锁”按钮略有些影响观瞻，尤其是该图位于长篇大论中时；如果不显示“解锁”按钮，那这个不受多余东西影响的图就整洁、美观了许多，甚至不亚于OneNote；至于“解锁”功能，可以放置在右击菜单中。
以上就是本人的一点小小的建议，望你的挂件越做越好，福泽广大用户。

**Comment by dicarne** [comment]
建议不错，改进了，提交官方了，等待一些时间之后可以试一下~
不过我的笔没有右键功能，于是解锁换成一个小锁，比原本的美观很多，不会有碍事的底部栏了。

**Comment by sun7sun7sun7sun7** [comment]
非常感谢您的改进，现在笔记中的图看起来非常舒服。
另外，我想再提两个小小的建议：若“撤销”按钮旁有个“恢复”按钮就更好了。如果底部栏中有一个铅笔图标和一个橡皮图标，选中前者可以画图，选中后者可以擦除，那就更完美了。
以上便是本人的一点小小的建议。由衷地敬佩您无私奉献的精神，这是我们广大用户的福音。

**Comment by sun7sun7sun7sun7** [comment]
再次感谢你的改进，如今该挂件的功能近乎完美了。
只是使用过程中发现了一个bug。我的操作如下：在软件中打开该挂件→画图→锁定→拉动窗口右下角改变窗口大小→关闭软件再打开软件。结果原先画的图就没了。
希望能解决，谢谢！

**Comment by dicarne** [comment]
研究了一下，感觉是笔记的bug，不过可以用“不是那么科学的”办法修复一下

**Comment by dicarne** [comment]
https://ld246.com/article/1651545584817
看看D大会不会修吧22

**Comment by dicarne** [comment]
当时这么搞是因为在pad上笔没有右键……不过你的建议很好，我看看怎么搞
